name: run-notebooks-test
on:
  push: 
    branches:
      - main
    paths:
      - ".github/workflows/**"
  pull_request:
    branches:
      - main
    paths:
      - ".github/workflows/**"
jobs:
  build:
    runs-on: ubuntu-latest 
    steps:
    - name: check out repo
      uses: actions/checkout@v2
    - name: setup python
      uses: actions/setup-python@v2
      with: 
        python-version: "3.6"
    - name: pip install
      run: pip install -r requirements.txt
    - name: azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
    - name: install azmlcli
      #run: az extension add -s https://azurecliext.blob.core.windows.net/release/azure_cli_ml-1.15.0-py3-none-any.whl -y
      run: az extension add -n azure-cli-ml
    - name: attach to workspace
      run: az ml folder attach -w azureml-chuden -g chuden
    - name: run notebook
      run: papermill examples/3-aml-run.ipynb -k python
